class AnalyticsConfig:
    HEAD_DEVIATION_SCALE = 150.0
    EYE_DEVIATION_SCALE = 500.0
    FOCUS_EYE_WEIGHT = 0.7
    FOCUS_HEAD_WEIGHT = 0.3

    POSTURE_ALIGNMENT_SCALE = 400.0

    VITALITY_BASE_SCORE = 50.0
    VITALITY_HAND_BONUS = 10.0
    VITALITY_MOUTH_GAP_SCALE = 500.0
    VITALITY_MAX_HANDS_COUNTED = 2

    PRESENCE_ELBOW_DISTANCE_SCALE = 200.0

    COMPOSURE_FACE_HAND_DISTANCE_LIMIT = 0.15
    COMPOSURE_HAND_NEAR_FACE_PENALTY = 20.0

    DEFAULT_SCORE = 100.0
    MIN_SCORE = 0.0
    MAX_SCORE = 100.0
