services:
  backend:
    build:
      context: ./backend
    container_name: smart-presence-backend
    ports:
      - "8000:8000"
    environment:
      RELOAD: "true"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: smart-presence-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

