name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t smart-presence-backend:latest ./backend

      - name: Run backend tests on built image
        run: docker run --rm smart-presence-backend:latest pytest /app/tests/automatic
