name: CI CD 

on:
  push:
  pull_request:
    branches: [main]

jobs:
    CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t smart-presence-backend ./backend

      - name: Run backend tests
        run: docker run --rm smart-presence-backend pytest 

   